# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='accountemailcash',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_cash', to='users.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='accountemailcash',
            unique_together=set([('account', 'email')]),
        ),
    ]
