# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
