# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171029_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('house', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.Address'),
        ),
    ]
