INVALID_AUTH = 'Неправильный логин/пароль'
PASSWORD_INCORRECT = 'Пароли не совпадают'
NO_PERMISSION = 'Нет прав доступа к этому действию'
NO_SUCH_PRODUCT = 'Такого инструмента найдено не было'
INCORRECT_INVOICE_TYPE = 'Неправильный тип заявки'
INCORRECT_INVOICE_PRODUCTS = 'Нельзя создавать заявку состоящую из своих и чужих инструментов'
ADDRESS_INCONSISTENCY = 'Можно указать либо существующий адресс, либо кастомный'
INCORRECT_TARGET = 'Неправильная цель заявки'
INCORRECT_ID_PATTERN = '{} с pk={} не найден'
SOME_PRODUCTS_ARE_IN_TRANSITION = 'Некоторые из выбранных инструментов находятся в пути'
INVOICE_UPDATE_ERROR = 'Нельзя перескакивать между статусами заявки'
ALREADY_EXIST_USER = 'Пользователь с таким эмейл уже существует'
TO_ACCOUNT_REQUIRED = 'Поле "Кому" должно быть обязательно заполнено'
