INVALID_AUTH = 'Неправильный логин/пароль'
PASSWORD_INCORRECT = 'Пароли не совпадают'
NO_PERMISSION = 'Нет прав доступа к этому действию'
NO_SUCH_PRODUCT = 'Такого инструмента найдено не было'
INCORRECT_INVOICE_TYPE = 'Неправильный тип заявки'
INCORRECT_INVOICE_PRODUCTS = 'Нельзя создавать заявку состоящую из своих и чужих инструментов'
ADDRESS_INCONSISTENCY = 'Можно указать либо существующий адресс, либо кастомный'
INCORRECT_TARGET = 'Неправильная цель заявки'
INCORRECT_ID_PATTERN = '{} с pk={} не найден'
