# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20171031_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('target', models.IntegerField(choices=[(0, 'Выставка'), (1, 'Демонстрация'), (2, 'Семинар'), (3, 'Возврат')], null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_invoices', to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Создано'), (1, 'В обработке'), (2, 'Отдано курьерам'), (3, 'Принято от курьера')])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_changes', to='products.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.SlugField(max_length=255, unique=True)),
                ('number', models.FloatField(blank=True)),
                ('number_for_order', models.CharField(max_length=10)),
                ('quantity', models.BigIntegerField(default=0)),
                ('location_update', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=255)),
                ('on_repair', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.Account')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_lines',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_invoices', to='users.Account'),
        ),
    ]
