# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171103_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='on_creation',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.IntegerField(choices=[(0, 'Получение'), (1, 'Отправка'), (2, 'Ремонт')], default=0),
        ),
    ]
