# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171106_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_filter',
            field=models.CharField(db_index=True, default='', max_length=255, null=True),
        ),
    ]
