# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171106_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создано'), (1, 'В обработке'), (2, 'Отдано курьерам'), (3, 'Принято от курьера'), (4, 'Закрыто')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='on_transition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicechanges',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создано'), (1, 'В обработке'), (2, 'Отдано курьерам'), (3, 'Принято от курьера'), (4, 'Закрыто')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_filter',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
