# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20171107_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='invoice',
            name='track_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'В обработке'), (1, 'Отдано курьерам'), (2, 'Принято от курьера'), (3, 'Закрыто')], default=0),
        ),
        migrations.AlterField(
            model_name='invoicechanges',
            name='status',
            field=models.IntegerField(choices=[(0, 'В обработке'), (1, 'Отдано курьерам'), (2, 'Принято от курьера'), (3, 'Закрыто')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_for_order',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
