# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171207_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inner_type_filter',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
