# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171208_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_for_order',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
