# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20171208_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
